src/components/Alarm/Alarm.module.scss
src/components/Footer/footer.module.scss
src/components/Layout/Layout.tsx
src/components/Layout/layout.module.css
src/components/SideBar/SideBar.module.scss
src/components/SideBar/SideBar.tsx
src/pages/index.tsx
src/styles/globals.css

- 레이아웃 컴포넌트 생성
- footer에 fixed 속성을 추가해서 화면 밑부분에 고정했습니다.
-  레이아웃컴포넌트에 children 프롭스를 통해 레이아웃을 제외한부분을 갈아끼울수있게 만들었습니다
레이아웃 처리에 더 좋은아이디어가 있으면 알려주세요!

💄 Design:레이아웃 컴포넌트 디자인

---

src/utils/instance.ts

[Feat] axios instance 파일 추가

---

package-lock.json
package.json
public/assets/icons/close.svg
src/components/DetailClass/DetailClass.tsx
src/components/DetailClass/calendar/CalendarComponent.tsx
src/components/DetailClass/calendar/calendarComponent.module.scss
src/components/DetailClass/modal/Modal.tsx
src/components/DetailClass/modal/modal.module.scss
src/components/DetailClass/reservation/Reservation.tsx
src/components/DetailClass/reservationModal/ReservationModal.tsx
src/components/DetailClass/reservationModal/reservationModal.module.scss

> 사용 확정은 아니지만 일단 리액트 캘린더 라이브러리 넣어봤는데 css 커스텀이 왜 안되는지 모르겠습니다😭😭

[design] 예약 모달 퍼블리싱

---

src/components/DetailClass/modal/Modal.tsx

[Hotfix] 오류 수정

---

src/pages/class-info/[id]/index.tsx
src/pages/my-page/index.tsx
src/pages/my-page/manage-reservation/index.tsx
src/pages/my-page/my-class/index.tsx
src/pages/my-page/my-reservation/index.tsx
src/pages/sign-in/index.tsx
src/pages/sign-up/index.tsx

[Hotfix] 임시로 빈 파일 채우기

---

src/apis/activitiesApi.ts

util폴더에 있던 instance 가 포함된 코드들 수정

[🚑️ Hotfix:]Api instance 수정

---

src/apis/authApi.ts
src/apis/getReservationDashboardApi.ts
src/components/Calendar/Calendar.tsx
src/components/Select/Select.tsx
src/containers/CalendarContainer/CalendarContainer.tsx
src/containers/SelectContainer/SelectContainer.tsx
src/pages/_app.tsx
src/pages/manage-reservation/index.tsx
src/store/idAtom.ts

_app 에 recoilroot 로 감싸서 적용했습니다.

🔧 Setting: 리코일 세팅

---

src/apis/activitiesApi.ts
src/components/Calendar/Calendar.css
src/components/Calendar/Calendar.tsx
src/components/DetailClass/DetailClass.tsx
src/components/DetailClass/classTitle/classTitle.module.scss
src/components/DetailClass/description/description.module.scss
src/components/DetailClass/modal/modal.module.scss
src/components/DetailClass/reservation/Reservation.tsx
src/components/DetailClass/reservation/reservation.module.scss
src/components/DetailClass/reservationModal/ReservationModal.tsx
src/components/DetailClass/reservationModal/reservationModal.module.scss
src/components/DetailClass/review_/Review.tsx
src/components/DetailClass/review_/review.module.scss
src/components/Header/Header.tsx
src/containers/ReservationCalendar/ReservationCalendar.tsx
src/pages/class-info/[id]/index.tsx
src/types/activitiesType/ActivitiesType.ts

캘린더 라이브러리 css 수정,
율민님과 제가 테스트하는 이메일이 달라서 헤더 로그인 옆에 버튼 누르면 로그인되게 수정했습니다.
css로 고통받는중......🫠
>

[Design] 캘린더 반응형 수정 및 자잘한 수정

---

src/components/Modal2/Modal2Base.tsx
src/components/Modal2/modal2Base.module.scss
src/containers/ModalContainer/ModalContainer.tsx
src/pages/manage-reservation/index.tsx

모달의 베이스가 되는 컴포넌트와 컨테이너를 작성했습니다. css는 미완
프롭스에 size는 값을 입력할시 그값이 모달바디 부분의 클래스로 들어갑니다.
프롭스로 클래스를 내려주고 scss파일에 해당 클래스의 스타일을 추가해주면됩니다.
추가해야할부분이나 수정해야할부분이있으면 말씀해주세요

[✨ Feat] 모달 베이스  컴포넌트&컨테이너 생성

---

src/apis/myActivitiesApi.ts
src/components/Calendar/Calendar.tsx
src/components/Calendar/MiniCalendar/MiniCalendar.tsx
src/components/DetailClass/miniCalendarContainer/MiniCalendarContainer.tsx
src/components/DetailClass/modal/Modal.tsx
src/components/Header/Header.tsx
src/components/Input/Input.tsx
src/components/Modal2/ReserveInfoModal/ReserveInfoModal.tsx
src/containers/CalendarContainer/CalendarContainer.tsx
src/containers/ReservationCalendar/ReservationCalendar.tsx
src/containers/SelectContainer/SelectContainer.tsx
src/containers/mainPage/ClassCardList/ClassCardAfterSearch.tsx
src/pages/my-page/manage-reservation/index.tsx
src/pages/my-page/my-reservation/index.tsx

[Hotfix] 배포 오류 수정

---

package-lock.json
package.json
src/apis/myActivitiesApi.ts
src/components/MyClass/MyClassCard/MyClassCard.tsx
src/components/MyClass/MyClassCard/myClassCard.module.scss
src/pages/my-page/my-class/index.module.scss
src/pages/my-page/my-class/index.tsx
src/styles/globals.css
src/types/activitiesType/MyActivityType.ts

[Feat] 내 체험 관리 페이지 

---

src/components/Header/Header.tsx

[Fix] 에러 해결

---

src/apis/axiosInstance.ts
src/components/Header/Header.tsx
src/components/Header/header.module.scss

[Fix] header 액세스 토큰에 따라 다르게 리렌더링

---

src/components/DetailClass/DetailClass.tsx
src/components/DetailClass/classTitle/ClassTitle.tsx
src/components/DetailClass/classTitle/classTitle.module.scss
src/components/DetailClass/description/description.module.scss
src/components/DetailClass/image_/Image.tsx
src/components/DetailClass/image_/image.css
src/components/DetailClass/image_/image.module.scss
src/components/DetailClass/review_/review.module.scss
src/components/Input/AuthInput/AuthInput.tsx
src/pages/_app.tsx
src/pages/sign-up/index.module.scss
src/pages/sign-up/index.tsx

[Chore] 상세페이지 이미지 크기 줄임, 회원가입 유효성 검사 추가

---

src/components/Calendar/MiniCalendar/MiniCalendar.tsx
src/components/DetailClass/miniCalendarContainer/MiniCalendarContainer.tsx
src/components/mainPage/BestClassCard/bestClassCard.module.scss
src/components/mainPage/ClassCard/classCard.module.scss

[Fix] 예약 안되는 에러 해결

---

src/apis/getMyReservation.ts
src/apis/myActivitiesApi.ts
src/apis/usersApi.ts
src/components/Alarm/Alarm.tsx
src/components/Input/AuthInput/AuthInput.tsx
src/components/Modal2/ReserveInfoModal/ReserveInfoModal.tsx
src/pages/my-page/manage-reservation/index.tsx
src/pages/sign-up/index.tsx

[Hotfix] 3차 배포 오류 수정

---

package-lock.json
package.json
src/apis/authApi.ts
src/apis/axiosInstance.ts
src/components/Header/Header.tsx

- js쿠키 라이브러리 추가하고 토큰을 쿠키로 처리하게 해줬습니다.
- axiosinstance 파일에 리프레시토큰 처리기능 추가됨.

♻️ Refactor: 액세스토큰 쿠키처리,리프레쉬토큰 처리기능추가

---

src/apis/axiosInstance.ts

refreshtoken 쪽 수정입니다.
간단한내용이라 어프롭없이 머지하겠습니다.

🐛 Fix: axiosinstance 수정

---

src/components/MyClass/MyClassInputs/AddressInput/addressInput.module.scss
src/components/MyClass/MyClassInputs/ImageInput/ImageInput.tsx
src/components/MyClass/MyClassInputs/ImageInput/SubImgaeInput.tsx
src/components/MyClass/MyClassTitle/EditMyClass.tsx
src/components/MyClass/MyClassTitle/MyClassTitle.tsx
src/components/MyClass/MyClassTitle/myClassTitle.module.scss
src/containers/ImageInput/EditBannerImageInputContainer.tsx
src/containers/ImageInput/SubImageInputContainer.tsx
src/pages/my-page/my-class/edit-class/[id]/index.tsx

[Refactor] 내 체험 등록하기 기능 리팩토링

---

src/apis/activitiesApi.ts
src/components/Calendar/Calendar.css
src/components/Calendar/MiniCalendar/MiniCalendar.tsx
src/components/DetailClass/miniCalendarContainer/MiniCalendarContainer.tsx
src/components/DetailClass/miniCalendarContainer/miniCalendarContainer.module.scss
src/components/DetailClass/reservation/reservation.module.scss
src/components/DetailClass/review_/review.module.scss

달력 데이터 불러오기 및 회의록에 작성했던 자잘한 부분들 수정했습니다.
카카오맵은 건드리지 않았는데 왜 저한텐 잘 보이는걸까요...😟😟
>

✨ chore : 달력 데이터 받아오기 수정 및 자잘한 수정

---

src/components/DarkModeToggle/DarkModeToggle.tsx
src/components/MyClass/MyClassCard/myClassCard.module.scss
src/components/Select/select.module.scss
src/containers/ProfileInfoChangeForm/ProfileInfoChangeForm.module.scss

🐛 Fix: 다크모드 css수정

---

src/components/mainPage/Banner/banner.module.scss
src/components/mainPage/CategoryBar/CategoryBar.tsx
src/containers/mainPage/Banner/bannerContainer.module.scss
src/containers/mainPage/BestClassList/BestCardList.tsx
src/containers/mainPage/CategoryBarContainer/CategoryBarContainer.tsx
src/pages/index.module.scss

[Style] 사소한 스타일들 수정 및 최신순 정렬 추가
